version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:4.1'
    ports:
      - "27017:27017"
    volumes:
      - './data/mongodb:/bitnami'

  redis:
    image: 'bitnami/redis:latest'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6380:6379'
    volumes:
      - './data/redis:/bitnami/redis/data'
